import { expect, test } from 'vitest'

import { transliterate } from './transliteration'

test.each([
  ['Аа', 'Aa', 'Алушта', 'Alushta'],
  ['Аа', 'Aa', 'Андрій', 'Andrii'],
  ['Бб', 'Bb', 'Борщагівка', 'Borshchahivka'],
  ['Бб', 'Aa', 'Борисенко', 'Borysenko'],
  ['Вв', 'Vv', 'Вінниця', 'Vinnytsia'],
  ['Вв', 'Vv', 'Володимир', 'Volodymyr'],
  ['Вв', 'Vv', 'Вінниця', 'Vinnytsia'],
  ['Вв', 'Vv', 'Володимир', 'Volodymyr'],
  ['Гг', 'Hh', 'Гадяч', 'Hadiach'],
  ['Гг', 'Hh', 'Богдан', 'Bohdan'],
  ['Гг', 'Hh', 'Згурський', 'Zghurskyi'],
  ['Ґґ', 'Gg', 'Ґалаґан', 'Galagan'],
  ['Ґґ', 'Gg', 'Ґорґани', 'Gorgany'],
  ['Дд', 'Dd', 'Донецьк', 'Donetsk'],
  ['Дд', 'Dd', 'Дмитро', 'Dmytro'],
  ['Ее', 'Ee', 'Рівне', 'Rivne'],
  ['Ее', 'Ee', 'Олег', 'Oleh'],
  ['Ее', 'Ee', 'Есмань', 'Esman'],
  ['Єє', 'Ye', 'Єнакієве', 'Yenakiieve'],
  ['Єє', 'ie', 'Гаєвич', 'Haievych'],
  ['Єє', 'ie', "Короп'є", 'Koropie'],
  ['Жж', 'Zh', 'Житомир', 'Zhytomyr'],
  ['Жж', 'Zh', 'Жанна', 'Zhanna'],
  ['Жж', 'Zh', 'Жежелів', 'Zhezheliv'],
  ['Зз', 'Zz', 'Закарпаття', 'Zakarpattia'],
  ['Зз', 'Zz', 'Казимирчук', 'Kazymyrchuk'],
  ['ЗзГг', 'Zgh', 'Згорани', 'Zghorany'],
  ['ЗзГг', 'Zgh', 'Розгон', 'Rozghon'],
  ['Ии', 'Yy', 'Медвин', 'Medvyn'],
  ['Ии', 'Yy', 'Михайленко', 'Mykhailenko'],
  ['Іі', 'Ii', 'Іванків', 'Ivankiv'],
  ['Іі', 'Ii', 'Іващенко', 'Ivashchenko'],
  ['Її', 'Yi', 'Їжакевич', 'Yizhakevych'],
  ['Її', 'i', 'Кадиївка', 'Kadyivka'],
  ['Її', 'i', "Мар'їне", 'Marine'],
  ['Йй', 'Y', 'Йосипівка', 'Yosypivka'],
  ['Йй', 'i', 'Стрий', 'Stryi'],
  ['Йй', 'i', 'Олексій', 'Oleksii'],
  ['Кк', 'Kk', 'Київ', 'Kyiv'],
  ['Кк', 'Kk', 'Коваленко', 'Kovalenko'],
  ['Лл', 'Ll', 'Лебедин', 'Lebedyn'],
  ['Лл', 'Ll', 'Леонід', 'Leonid'],
  ['Мм', 'Mm', 'Миколаїв', 'Mykolaiv'],
  ['Мм', 'Mm', 'Маринич', 'Marynych'],
  ['Нн', 'Nn', 'Ніжин', 'Nizhyn'],
  ['Нн', 'Nn', 'Наталія', 'Nataliia'],
  ['Оо', 'Oo', 'Одеса', 'Odesa'],
  ['Оо', 'Oo', 'Онищенко', 'Onyshchenko'],
  ['Пп', 'Pp', 'Полтава', 'Poltava'],
  ['Пп', 'Pp', 'Петро', 'Petro'],
  ['Рр', 'Rr', 'Решетилівка', 'Reshetylivka'],
  ['Рр', 'Rr', 'Рибчинський', 'Rybchynskyi'],
  ['Сс', 'Ss', 'Суми', 'Sumy'],
  ['Сс', 'Ss', 'Соломія', 'Solomiia'],
  ['Тт', 'Tt', 'Тернопіль', 'Ternopil'],
  ['Тт', 'Tt', 'Троць', 'Trots'],
  ['Уу', 'Uu', 'Ужгород', 'Uzhhorod'],
  ['Уу', 'Uu', 'Уляна', 'Uliana'],
  ['Фф', 'Ff', 'Фастів', 'Fastiv'],
  ['Фф', 'Ff', 'Філіпчук', 'Filipchuk'],
  ['Хх', 'Kh', 'Харків', 'Kharkiv'],
  ['Хх', 'Kh', 'Христина', 'Khrystyna'],
  ['Цц', 'Ts', 'Біла Церква', 'Bila Tserkva'],
  ['Цц', 'Ts', 'Стеценко', 'Stetsenko'],
  ['Чч', 'Ch', 'Чернівці', 'Chernivtsi'],
  ['Чч', 'Ch', 'Шевченко', 'Shevchenko'],
  ['Шш', 'Sh', 'Шостка', 'Shostka'],
  ['Шш', 'Sh', 'Кишеньки', 'Kyshenky'],
  ['Щщ', 'Shch', 'Щербухи', 'Shcherbukhy'],
  ['Щщ', 'shch', 'Гоща', 'Hoshcha'],
  ['Щщ', 'shch', 'Гаращенко', 'Harashchenko'],
  ['Ьь', '', 'Український', 'Ukrainskyi'],
  ['Ьь', '', 'Чинність', 'Chynnist'],
  ['Юю', 'Yu', 'Юрій', 'Yurii'],
  ['Юю', 'iu', 'Корюківка', 'Koriukivka'],
  ['Яя', 'Ya', 'Яготин', 'Yahotyn'],
  ['Яя', 'Ya', 'Ярошенко', 'Yaroshenko'],
  ['Яя', 'ia', 'Костянтин', 'Kostiantyn'],
  ['Яя', 'ia', "Знам'янка", 'Znamianka'],
  ['Яя', 'ia', 'Феодосія', 'Feodosiia'],
])('[%s -> %s] transliterate("%s") -> "%s"', (_ua, _en, uaText, enText) => {
  expect(transliterate(uaText)).toBe(enText)
})